function openVideoMp3() {
  openModal(`<h2 class="modal-title">${t('videoToMp3')}</h2><p class="modal-subtitle">Uses FFmpeg WebAssembly. The first use downloads the processing engine.</p>${dropZone('videoFile','video/*')}
    <div class="form-grid"><div class="form-field"><label>MP3 bitrate</label><select id="mp3Bitrate"><option>128k</option><option selected>192k</option><option>256k</option><option>320k</option></select></div></div>
    <div class="progress-wrap hidden" id="mp3Progress"><div class="progress-bar"><span></span></div><div class="progress-text">Preparing...</div></div><div class="action-row"><button id="mp3Btn" class="primary-btn" disabled>Convert to MP3</button></div>`, () => {
      let file; bindDropZone('videoFile',files=>{file=files[0];$('#mp3Btn').disabled=!file;});
      $('#mp3Btn').onclick=async()=>{const btn=$('#mp3Btn'),wrap=$('#mp3Progress'),bar=$('.progress-bar span',wrap),text=$('.progress-text',wrap);btn.disabled=true;wrap.classList.remove('hidden');try{await loadFFmpeg();const {createFFmpeg,fetchFile}=FFmpeg;const ffmpeg=createFFmpeg({log:false,corePath:'https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js'});ffmpeg.setProgress(({ratio})=>{bar.style.width=`${Math.min(100,Math.max(0,ratio*100))}%`;text.textContent=`Processing ${Math.round(ratio*100)}%`;});text.textContent='Loading FFmpeg engine...';await ffmpeg.load();const input=`input_${Date.now()}.${file.name.split('.').pop()||'mp4'}`;const output=`${safeBase(file.name)}.mp3`;ffmpeg.FS('writeFile',input,await fetchFile(file));await ffmpeg.run('-i',input,'-vn','-b:a',$('#mp3Bitrate').value,output);const data=ffmpeg.FS('readFile',output);const blob=new Blob([data.buffer],{type:'audio/mpeg'});downloadBlob(blob,output);bar.style.width='100%';text.textContent='Completed';addHistory(t('videoToMp3'),output,formatBytes(blob.size));ffmpeg.exit();}catch(err){console.error(err);text.textContent='Could not load FFmpeg. Check your internet connection or try Chrome/Edge.';toast('Video conversion engine could not start.');}finally{btn.disabled=false;}};
  });
}

function openZip() {
  openModal(`<h2 class="modal-title">${t('fileCompressor')}</h2><p class="modal-subtitle">Select multiple files and package them into a ZIP archive.</p>${dropZone('zipFiles','*/*',true,'Click or drop multiple files here')}
    <div id="zipList" class="result-card hidden"></div><div class="form-grid"><div class="form-field full"><label>ZIP filename</label><input id="zipName" value="rom-project-files.zip"></div></div><div class="progress-wrap hidden" id="zipProgress"><div class="progress-bar"><span></span></div><div class="progress-text">Preparing...</div></div><div class="action-row"><button id="zipBtn" class="primary-btn" disabled>Create ZIP</button></div>`, () => {
      let files=[];bindDropZone('zipFiles',selected=>{files=[...selected];$('#zipBtn').disabled=!files.length;$('#zipList').classList.toggle('hidden',!files.length);$('#zipList').innerHTML=`<strong>${files.length} files selected</strong><br>${formatBytes(files.reduce((a,f)=>a+f.size,0))}`;});
      $('#zipBtn').onclick=async()=>{const zip=new JSZip(),wrap=$('#zipProgress');wrap.classList.remove('hidden');files.forEach(f=>zip.file(f.name,f));const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}},meta=>{$('.progress-bar span',wrap).style.width=meta.percent+'%';$('.progress-text',wrap).textContent=`Compressing ${Math.round(meta.percent)}%`;});const name=$('#zipName').value.trim()||'files.zip';downloadBlob(blob,name.endsWith('.zip')?name:name+'.zip');addHistory(t('fileCompressor'),name,`${files.length} files · ${formatBytes(blob.size)}`);};
  });
}

function openImagePdf() {
  openModal(`<h2 class="modal-title">${t('imageToPdf')}</h2><p class="modal-subtitle">Combine selected images into one A4 PDF.</p>${dropZone('pdfImages','image/*',true,'Select images in page order')}
    <div id="pdfList" class="result-card hidden"></div><div class="form-grid"><div class="form-field"><label>Page orientation</label><select id="pdfOrientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div class="form-field"><label>Image fit</label><select id="pdfFit"><option value="contain">Fit inside page</option><option value="cover">Fill page</option></select></div></div><div class="action-row"><button id="pdfBtn" class="primary-btn" disabled>Create PDF</button></div>`,()=>{
      let files=[];bindDropZone('pdfImages',selected=>{files=[...selected];$('#pdfBtn').disabled=!files.length;$('#pdfList').classList.toggle('hidden',!files.length);$('#pdfList').innerHTML=`<strong>${files.length} images selected</strong>`;});
      $('#pdfBtn').onclick=async()=>{const {jsPDF}=window.jspdf,orientation=$('#pdfOrientation').value,pdf=new jsPDF({orientation,unit:'mm',format:'a4'});const pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight();for(let i=0;i<files.length;i++){if(i)pdf.addPage();const img=await loadImage(files[i]),data=await fileToDataURL(files[i]);const mode=$('#pdfFit').value,scale=mode==='cover'?Math.max(pw/img.naturalWidth,ph/img.naturalHeight):Math.min(pw/img.naturalWidth,ph/img.naturalHeight);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;pdf.addImage(data,files[i].type.includes('png')?'PNG':'JPEG',(pw-w)/2,(ph-h)/2,w,h);}const name='rom-images.pdf';pdf.save(name);addHistory(t('imageToPdf'),name,`${files.length} pages`);};
  });
}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}

function openSizePresets() {
  const presets=[['Facebook Post','1200 × 1500'],['Square Post','1080 × 1080'],['Instagram Portrait','1080 × 1350'],['Story / Reels','1080 × 1920'],['YouTube Thumbnail','1280 × 720'],['YouTube Cover','2560 × 1440'],['Facebook Cover','1640 × 924'],['A4 Print 300 DPI','2480 × 3508']];
  openModal(`<h2 class="modal-title">${t('sizePresets')}</h2><p class="modal-subtitle">Click a preset to copy its dimensions.</p><div class="presets-grid">${presets.map(([n,s])=>`<button class="preset-card" data-size="${s.replace(/ /g,'')}"><strong>${n}</strong><span>${s}px</span></button>`).join('')}</div>`,()=>{$$('.preset-card',modalContent).forEach(btn=>btn.onclick=()=>{navigator.clipboard.writeText(btn.dataset.size);toast(`Copied ${btn.dataset.size}`);addHistory(t('sizePresets'),btn.querySelector('strong').textContent,btn.dataset.size);});});
}

function openPalette() {
  openModal(`<h2 class="modal-title">${t('paletteExtractor')}</h2><p class="modal-subtitle">Extract five dominant color samples. Click a color to copy its HEX value.</p>${dropZone('paletteFile','image/*')}<div id="palettePreview" class="preview-area"><span class="muted">Preview</span></div><div id="paletteGrid" class="palette-grid"></div>`,()=>{
    bindDropZone('paletteFile',async files=>{const file=files[0];if(!file)return;const img=await loadImage(file);$('#palettePreview').innerHTML='';$('#palettePreview').append(img);const colors=extractPalette(img,5);$('#paletteGrid').innerHTML=colors.map(c=>`<div class="swatch" style="background:${c}" data-color="${c}"><span>${c}</span></div>`).join('');$$('.swatch').forEach(s=>s.onclick=()=>{navigator.clipboard.writeText(s.dataset.color);toast(`Copied ${s.dataset.color}`);});addHistory(t('paletteExtractor'),file.name,colors.join(', '));});
  });
}
function extractPalette(img,count){const c=document.createElement('canvas');c.width=80;c.height=80;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,80,80);const data=ctx.getImageData(0,0,80,80).data,bins={};for(let i=0;i<data.length;i+=16){const a=data[i+3];if(a<180)continue;const r=Math.round(data[i]/32)*32,g=Math.round(data[i+1]/32)*32,b=Math.round(data[i+2]/32)*32,key=`${Math.min(r,255)},${Math.min(g,255)},${Math.min(b,255)}`;bins[key]=(bins[key]||0)+1;}return Object.entries(bins).sort((a,b)=>b[1]-a[1]).slice(0,count).map(([k])=>'#'+k.split(',').map(v=>(+v).toString(16).padStart(2,'0')).join('').toUpperCase());}

function openQr() {
  openModal(`<h2 class="modal-title">${t('qrGenerator')}</h2><p class="modal-subtitle">Create a QR code from a link, text or contact information.</p><div class="form-field"><label>Text or URL</label><textarea id="qrText" rows="4" placeholder="https://example.com"></textarea></div><div class="form-grid"><div class="form-field"><label>Size</label><select id="qrSize"><option>256</option><option>512</option><option>1024</option></select></div></div><div id="qrPreview" class="preview-area"><span class="muted">QR preview</span></div><div class="action-row"><button id="qrCreate" class="secondary-btn">Generate</button><button id="qrDownload" class="primary-btn" disabled>Download PNG</button></div>`,()=>{
    $('#qrCreate').onclick=()=>{const text=$('#qrText').value.trim();if(!text)return toast('Enter text or a URL.');const size=+$('#qrSize').value,preview=$('#qrPreview');preview.innerHTML='';new QRCode(preview,{text,width:size,height:size,correctLevel:QRCode.CorrectLevel.H});$('#qrDownload').disabled=false;};
    $('#qrDownload').onclick=()=>{const canvas=$('#qrPreview canvas'),img=$('#qrPreview img');if(canvas)canvas.toBlob(blob=>downloadBlob(blob,'rom-qr-code.png'));else if(img){fetch(img.src).then(r=>r.blob()).then(b=>downloadBlob(b,'rom-qr-code.png'));}addHistory(t('qrGenerator'),'rom-qr-code.png','PNG');};
  });
}
